version: "3"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE: graphql_books
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
    ports:
      - 3306:3306
    volumes:
      - ./.docker/mysql:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    secrets:
      - mysql_root_password
      - mysql_password

secrets:
  mysql_root_password:
    file: ./.docker/mysql_root_password.txt
  mysql_password:
    file: ./.docker/mysql_password.txt
volumes:
  db_data: